# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='shortened_url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
