# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortener_end_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='end_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
