# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20171019_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
